#                                                  NumPy

In [1]:
import numpy as np

## NumPy array

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
nums = [[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]]

In [4]:
num = np.array(nums)

In [5]:
num

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [6]:
num.size

24

In [7]:
num.ndim # dimentions

3

In [8]:
num.shape  # 3x2x4

(3, 2, 4)

In [9]:
num.dtype # arrays contain only one type of data types that's why numpy is fast

dtype('int64')

In [10]:
# 1-d array ==> vector
# 2-d array ==> matrix
# 3-d array ==> tensor

In [11]:
# numpy is fast bz it has binding with C -lang



## zeros , ones , eye , diag , randint , rand , randn



In [12]:
arr1 = np.zeros(6)
arr1

array([0., 0., 0., 0., 0., 0.])

In [13]:
arr2 = np.zeros((3,3))        # All Zeroes
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr99 = np.empty((2,3))            # creates random array
arr99

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr3 = np.ones((3,3,3))       # All Ones
arr3 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
arr4 = np.eye(4)       # Diagonal elements 1
arr4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr5 = np.eye(3,4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [18]:
arr6 = np.diag([1,2,3,4])       # Diagonal elements as given array
arr6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
randArr = np.random.randint(1,15,100) # it includes 1 but not 15
randArr

array([10, 12,  1, 14,  6, 12,  1,  5,  6,  4,  6, 10,  9,  2, 13,  7, 10,
       14, 13, 12, 11,  5, 11, 13,  2,  4,  9,  7,  7,  6,  4,  8,  3, 12,
        6,  3,  6,  7,  6,  4,  1, 11,  6,  3,  1,  7,  6,  2, 12,  4, 11,
       10,  1,  7,  3,  7,  8,  1, 10, 14,  6, 12, 12, 10, 14,  3, 11,  9,
        5,  9,  6,  4,  6,  5, 11,  7,  5, 14,  3,  2,  6,  5,  5,  6, 13,
        1,  6,  7, 12,  5,  5, 11,  1,  3, 12,  5, 11, 10,  7, 10])

In [20]:
randArr2 = np.random.rand(10) 
randArr2

array([0.57358581, 0.5690522 , 0.84597823, 0.78275654, 0.97555427,
       0.60580529, 0.8218741 , 0.26210099, 0.07050418, 0.21557572])

In [21]:
randArr3 = np.random.rand(2,3) 
randArr3

array([[0.03287811, 0.98811492, 0.43420214],
       [0.28987826, 0.64133548, 0.43781646]])

In [22]:
randArr4 = np.random.randn(10)  # randn ==> mean nearly 0
randArr4

array([ 0.4476205 ,  1.20334951,  1.81421516, -1.38694481,  2.09860137,
        0.76299002, -0.99453368,  0.13650602,  1.87346491, -0.18227094])

In [23]:
randArr5 = np.random.randn(1000000)  # randn ==> mean nearly 0
np.mean(randArr5)

-0.0003402365698478398

## Same Random number using 'seed'

In [24]:
np.random.seed(123)     # 123 is any random number (to get same nums this random num need to be same) 
arr0 = np.random.randint(0,11,10)
arr0

array([ 2,  2,  6,  1,  3, 10,  9,  6,  1,  0])

## Reshaping of Data

In [25]:
randArr6 = np.random.randint(1,21,15)
randArr6

array([18, 16, 10,  1, 15,  1, 16, 20, 15,  5,  1, 17,  5, 18,  4])

In [26]:
randArr6 = randArr6.reshape(3,5)     # 2-D : 3-rows & 5-coulums
randArr6

array([[18, 16, 10,  1, 15],
       [ 1, 16, 20, 15,  5],
       [ 1, 17,  5, 18,  4]])

In [27]:
randArr6 = randArr6.reshape(5,-1)     #  -1 ==> decides it's own accordingly
randArr6

array([[18, 16, 10],
       [ 1, 15,  1],
       [16, 20, 15],
       [ 5,  1, 17],
       [ 5, 18,  4]])

In [28]:
randArr6 = randArr6.reshape(15)     # 1-D
randArr6

array([18, 16, 10,  1, 15,  1, 16, 20, 15,  5,  1, 17,  5, 18,  4])

## Indexing & Slicing

In [29]:
arr7 = np.random.randint(0,101,10)
arr7

array([ 2, 84, 39, 66, 84, 47, 61, 48,  7, 99])

In [30]:
arr7[0]

2

In [31]:
arr7[-1]

99

In [32]:
arr7[:]

array([ 2, 84, 39, 66, 84, 47, 61, 48,  7, 99])

In [33]:
arr7[::2]

array([ 2, 39, 84, 61,  7])

In [34]:
arr7[::-1]

array([99,  7, 48, 61, 47, 84, 66, 39, 84,  2])

In [35]:
arr7[-3:]

array([48,  7, 99])

In [36]:
arr7[:-3]

array([ 2, 84, 39, 66, 84, 47, 61])

In [37]:
arr7[-3::-1]

array([48, 61, 47, 84, 66, 39, 84,  2])

### 2-D & 3-D

In [38]:
arr2D = np.random.randint(1,13,12).reshape(3,4)
arr2D

array([[ 5,  7,  2,  6],
       [ 7, 12,  3,  2],
       [ 9,  4, 11,  6]])

In [39]:
arr2D[1][3]

2

In [40]:
arr2D[1,3]

2

In [41]:
arr2D[:2,:2]

array([[ 5,  7],
       [ 7, 12]])

## View vs Copy

In [42]:
np.random.seed(123)
arr8 = np.random.randint(0,101,10)
arr8

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [43]:
arr9 = arr8[3:8]       # accessing same location 
arr9

array([17, 83, 57, 86, 97])

In [44]:
arr9[:] = 0
arr9

array([0, 0, 0, 0, 0])

In [45]:
arr8

array([66, 92, 98,  0,  0,  0,  0,  0, 96, 47])

In [46]:
arr10 = arr8[:3].copy()      # making seperate copy
arr10

array([66, 92, 98])

In [47]:
arr10[:]=0
arr10

array([0, 0, 0])

In [48]:
arr8

array([66, 92, 98,  0,  0,  0,  0,  0, 96, 47])

## Conditional Selection

In [49]:
arr00 = np.arange(1,11)
arr00

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
geaterthan4 = arr00>4
geaterthan4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr00[geaterthan4]

array([ 5,  6,  7,  8,  9, 10])

In [52]:
arr00[arr00%2==0]

array([ 2,  4,  6,  8, 10])

In [53]:
arr00[arr00%2==0] = 0
arr00

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

## Operations with array


In [54]:
arr000 = np.arange(1,11)

In [55]:
arr000*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [56]:
arr000+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr000%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [58]:
arr000 ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [59]:
arr000/0   # with warning ==> gives infinity

/home/shiru/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [60]:
arrs1 = np.array([1,2,3,4])
arrs2 = np.array([5,6,7,8])
arrs3 = np.array([9,10,11,12])

In [61]:
arrs1+arrs2+arrs3  # shape should be same

array([15, 18, 21, 24])

In [62]:
arrs1**arrs2

array([    1,    64,  2187, 65536])

In [63]:
arrs11 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arrs12 = np.array([11,12,13,14,15,16,17,18,19]).reshape(3,3)

# Shape must be same

In [64]:
arrs11

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arrs12

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [66]:
arrs11+arrs12

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [67]:
arrs11*arrs12         # multiplication is elementwise  # not matrix multipication

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [68]:
arrs11.dot(arrs12.transpose())  # Matrix multiplication

array([[ 74,  92, 110],
       [182, 227, 272],
       [290, 362, 434]])

In [69]:
# np.cross(arrs11,arrs2)
# arrs11.ndim

## more NumPy Opertions 

In [70]:
np.random.seed(111)
arr22 = np.random.randint(1,101,10)
arr22

array([85, 85, 85, 87, 20, 42, 67, 83, 41, 72])

In [71]:
np.min(arr22)

20

In [72]:
np.argmin(arr22)       # position of min

4

In [73]:
np.max(arr22)

87

In [74]:
np.argmax(arr22)        # position of max

3

In [75]:
np.sqrt(arr22)

array([9.21954446, 9.21954446, 9.21954446, 9.32737905, 4.47213595,
       6.4807407 , 8.18535277, 9.11043358, 6.40312424, 8.48528137])

In [76]:
np.exp(arr22)        # powers of e=2.71828

array([8.22301271e+36, 8.22301271e+36, 8.22301271e+36, 6.07603023e+37,
       4.85165195e+08, 1.73927494e+18, 1.25236317e+29, 1.11286375e+36,
       6.39843494e+17, 1.85867175e+31])

In [77]:
np.sin(arr22)

array([-0.17607562, -0.17607562, -0.17607562, -0.82181784,  0.91294525,
       -0.91652155, -0.85551998,  0.96836446, -0.15862267,  0.25382336])

In [78]:
np.cos(arr22)

array([-0.98437664, -0.98437664, -0.98437664,  0.56975033,  0.40808206,
       -0.39998531, -0.5177698 ,  0.24954012, -0.98733928, -0.96725059])

In [79]:
np.linspace(1,100,33)      # 33 evenly spaced numbers bet 1-100

array([  1.     ,   4.09375,   7.1875 ,  10.28125,  13.375  ,  16.46875,
        19.5625 ,  22.65625,  25.75   ,  28.84375,  31.9375 ,  35.03125,
        38.125  ,  41.21875,  44.3125 ,  47.40625,  50.5    ,  53.59375,
        56.6875 ,  59.78125,  62.875  ,  65.96875,  69.0625 ,  72.15625,
        75.25   ,  78.34375,  81.4375 ,  84.53125,  87.625  ,  90.71875,
        93.8125 ,  96.90625, 100.     ])

In [80]:
zr = np.array([1,2,0,2,1,0,0,1],dtype='bool')
zr

array([ True,  True, False,  True,  True, False, False,  True])

## Shuffle & Unique 

In [81]:
np.random.seed(123)
arr33 = np.random.randint(1,15,15)
arr33

array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [82]:
np.random.shuffle(arr33)      # shuffle the same array
arr33

array([ 4,  2, 11, 12, 13,  2,  3,  7,  1,  2,  7,  3, 10, 10, 14])

In [83]:
np.unique(arr33)             # removes duplicates

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [84]:
np.unique(arr33).size

10

In [85]:
np.unique(arr33,return_index=True,return_counts=True)   

# gives array of unique elements
# 1st positions of elements in original array
# number of times : number repeated

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14]),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1]))

## Axis 

In [86]:
np.random.seed(123)
matrix=np.random.randint(1,11,9).reshape(3,3)
matrix

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [87]:
matrix.sum()

39

In [88]:
np.min(matrix)+np.max(matrix)

11

In [89]:
# Rows = 1 && Columns = 0

In [90]:
np.min(matrix,axis =1 )     # Row wise Min

array([3, 2, 1])

In [91]:
np.max(matrix,axis =0)     # Column wise Max 

array([ 7,  4, 10])

In [92]:
np.sum(matrix,axis=0)

array([12,  9, 18])

In [93]:
np.cumsum(matrix)          # cumulative sum

array([ 3,  6, 13, 15, 19, 29, 36, 38, 39])

In [94]:
np.cumsum(matrix,axis=1)

array([[ 3,  6, 13],
       [ 2,  6, 16],
       [ 7,  9, 10]])

In [95]:
np.product(matrix,axis=0)

array([42, 24, 70])

## Stacking Horizontally & Vertically

In [96]:
np.random.seed(123)
matrix1=np.random.randint(1,20,9).reshape(3,3)
matrix2=np.random.randint(20,40,9).reshape(3,3)
matrix1

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18]])

In [97]:
matrix2

array([[35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

In [98]:
np.hstack((matrix1,matrix2))

array([[14,  3,  3, 35, 29, 20],
       [ 7, 18, 11, 34, 20, 35],
       [ 2,  1, 18, 39, 34, 24]])

In [99]:
np.vstack((matrix1,matrix2))

array([[14,  3,  3],
       [ 7, 18, 11],
       [ 2,  1, 18],
       [35, 29, 20],
       [34, 20, 35],
       [39, 34, 24]])

## NumPy vs List

In [100]:
%timeit 2+3                     # %timeit gives average time to run this one step
print("Done")

6.61 ns ± 0.114 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)
Done


In [101]:
%timeit  [i**3 for i in range(1,4)]

909 ns ± 27.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [102]:
%%timeit                       # %timeit gives average time to run this complete cell
l=[]
for i in range(1,4):
    l.append(i**3)

890 ns ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [103]:
%timeit np.arange(1,4)**3

1.5 µs ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [104]:
%timeit  [i**3 for i in range(1,10000)]

2.35 ms ± 124 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [105]:
%%timeit    
l=[]
for i in range(1,10000):
    l.append(i**3)

2.55 ms ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [106]:
%timeit np.arange(1,10000)**3               ### almost 100 times faster

27 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [107]:
array01 = np.random.randint(1,15,15)
array01

array([ 1,  1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9, 14,  1,  8])

In [108]:
array01.argsort() # gives positions of each num(in increasing order) in original array 

array([ 0,  1, 13,  3,  6,  9,  5,  2,  7, 10,  4,  8, 14, 11, 12])

# ADD --> np.newaxis , broadcast

## newaxis

In [109]:
np.newaxis is None

True

In [110]:
arr333 = np.arange(1,11)
arr333

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
print(arr333.shape,arr333.ndim,sep="\n")
print(arr333[:,np.newaxis].shape,arr333[:,np.newaxis].ndim,sep="\n")
arr333[:,np.newaxis]

(10,)
1
(10, 1)
2


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [112]:
print(arr333[:,np.newaxis,np.newaxis].shape,arr333[:,np.newaxis,np.newaxis].ndim,sep="\n")
arr333[:,np.newaxis,np.newaxis]

(10, 1, 1)
3


array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]]])

In [113]:
print(arr333[np.newaxis,:,np.newaxis].shape,arr333[np.newaxis,:,np.newaxis].ndim,sep="\n")
arr333[np.newaxis,:,np.newaxis]

(1, 10, 1)
3


array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [114]:
print(arr333[np.newaxis,np.newaxis,:].shape,arr333[np.newaxis,np.newaxis,:].ndim,sep="\n")
arr333[np.newaxis,np.newaxis,:]

(1, 1, 10)
3


array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

## 2-D array

In [115]:
arr999 = np.arange(1,10).reshape(3,3)
arr999

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
print(arr999[:,np.newaxis].shape,arr999[:,np.newaxis].ndim,sep="\n")
arr999[:,np.newaxis]                            # add newaxis 

(3, 1, 3)
3


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [117]:
print(arr999[:,np.newaxis,1].shape,arr999[:,np.newaxis,1].ndim,sep="\n")
arr999[:,np.newaxis,1]                       # takes 1st column & gives dimentions

(3, 1)
2


array([[2],
       [5],
       [8]])

In [118]:
print(arr999[np.newaxis,:].shape,arr999[np.newaxis,:].ndim,sep="\n")
arr999[np.newaxis,:]

(1, 3, 3)
3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [119]:
print(arr999[np.newaxis,:,1].shape,arr999[np.newaxis,:,1].ndim,sep="\n")
arr999[np.newaxis,:,1]

(1, 3)
2


array([[2, 5, 8]])

In [120]:
print(arr999[...,np.newaxis].shape,arr999[...,np.newaxis].ndim,sep="\n")
arr999[...,np.newaxis]

(3, 3, 1)
3


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [121]:
print(arr999[...,np.newaxis,1].shape,arr999[...,np.newaxis,1].ndim,sep="\n")
arr999[...,np.newaxis,1]

(3, 1)
2


array([[2],
       [5],
       [8]])

## 3-D array


In [122]:
arr27 = np.arange(1,28).reshape(3,3,3)
arr27 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [123]:
arr27[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [124]:
arr27[np.newaxis,np.newaxis]

array([[[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],

         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],

         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]]])

In [125]:
print(arr27[np.newaxis,np.newaxis,1].shape)
arr27[np.newaxis,np.newaxis,1]                       # takes arr27[1] & add two times dimension initially

(1, 1, 3, 3)


array([[[[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]])

                                             The End