In [1]:
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import  mean_squared_error

In [2]:
diabetes = datasets.load_diabetes()

In [3]:
diabetes.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [4]:
print(diabetes.DESCR)
diabetes.data.shape

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

(442, 10)

In [19]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [7]:
diabetes.data[0:1]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613]])

In [18]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [20]:
print(diabetes.data.shape)
print(diabetes.data[:,np.newaxis].shape)
diabetes.data[:,np.newaxis]

(442, 10)
(442, 1, 10)


array([[[ 0.03807591],
        [ 0.05068012],
        [ 0.06169621],
        ...,
        [-0.00259226],
        [ 0.01990842],
        [-0.01764613]],

       [[-0.00188202],
        [-0.04464164],
        [-0.05147406],
        ...,
        [-0.03949338],
        [-0.06832974],
        [-0.09220405]],

       [[ 0.08529891],
        [ 0.05068012],
        [ 0.04445121],
        ...,
        [-0.00259226],
        [ 0.00286377],
        [-0.02593034]],

       ...,

       [[ 0.04170844],
        [ 0.05068012],
        [-0.01590626],
        ...,
        [-0.01107952],
        [-0.04687948],
        [ 0.01549073]],

       [[-0.04547248],
        [-0.04464164],
        [ 0.03906215],
        ...,
        [ 0.02655962],
        [ 0.04452837],
        [-0.02593034]],

       [[-0.04547248],
        [-0.04464164],
        [-0.0730303 ],
        ...,
        [-0.03949338],
        [-0.00421986],
        [ 0.00306441]]])

In [22]:
diabetes.data[0]

array([ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
       -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613])

In [15]:
diabetes.data[:,np.newaxis,0]

array([[ 0.03807591],
       [-0.00188202],
       [ 0.08529891],
       [-0.08906294],
       [ 0.00538306],
       [-0.09269548],
       [-0.04547248],
       [ 0.06350368],
       [ 0.04170844],
       [-0.07090025],
       [-0.09632802],
       [ 0.02717829],
       [ 0.01628068],
       [ 0.00538306],
       [ 0.04534098],
       [-0.05273755],
       [-0.00551455],
       [ 0.07076875],
       [-0.0382074 ],
       [-0.02730979],
       [-0.04910502],
       [-0.0854304 ],
       [-0.0854304 ],
       [ 0.04534098],
       [-0.06363517],
       [-0.06726771],
       [-0.10722563],
       [-0.02367725],
       [ 0.05260606],
       [ 0.06713621],
       [-0.06000263],
       [-0.02367725],
       [ 0.03444337],
       [ 0.03081083],
       [ 0.01628068],
       [ 0.04897352],
       [ 0.01264814],
       [-0.00914709],
       [-0.00188202],
       [-0.00188202],
       [ 0.00538306],
       [-0.09996055],
       [-0.06000263],
       [ 0.01991321],
       [ 0.04534098],
       [ 0

In [21]:
print(diabetes.data[:,:,np.newaxis].shape)
diabetes.data[:,:,np.newaxis]

(442, 10, 1)


array([[[ 0.03807591],
        [ 0.05068012],
        [ 0.06169621],
        ...,
        [-0.00259226],
        [ 0.01990842],
        [-0.01764613]],

       [[-0.00188202],
        [-0.04464164],
        [-0.05147406],
        ...,
        [-0.03949338],
        [-0.06832974],
        [-0.09220405]],

       [[ 0.08529891],
        [ 0.05068012],
        [ 0.04445121],
        ...,
        [-0.00259226],
        [ 0.00286377],
        [-0.02593034]],

       ...,

       [[ 0.04170844],
        [ 0.05068012],
        [-0.01590626],
        ...,
        [-0.01107952],
        [-0.04687948],
        [ 0.01549073]],

       [[-0.04547248],
        [-0.04464164],
        [ 0.03906215],
        ...,
        [ 0.02655962],
        [ 0.04452837],
        [-0.02593034]],

       [[-0.04547248],
        [-0.04464164],
        [-0.0730303 ],
        ...,
        [-0.03949338],
        [-0.00421986],
        [ 0.00306441]]])